Algoritmo "números"

Var
numero: real
antecessor: real
sucessor: real


Inicio
 Escreva("Digite um numero: ")
   Leia (numero)

   antecessor<- numero -1
   sucessor<-numero +1
   
Escreval (" o número ", numero, " tem como antecessor o número ", antecessor, " e como sucessor o número ", sucessor, ".")
Fimalgoritmo

//6) Faça um programa que leia um número inteiro e
//mostre o seu antecessor e seu sucessor. Ex:
//Digite um número: 9 O antecessor de 9 é 8 O sucessor de 9 é 10